## Módulo 2 : Estadística y Visualización de Datos
#### Sesión : 01
#### Fecha : 01/08/20206
#### Autor : Jaime Gómez


In [45]:
print("Módulo 2 : Estadística y Visualización de Datos")

Módulo 2 : Estadística y Visualización de Datos


**1. Introducción a Numpy** 

Documentación de Numpy : https://numpy.org/doc/2.5/reference/index.html

In [46]:
import numpy as np

# Creando un array a partir de una lista de Python
lista = [1, 2, 3, 4, 5]
# Creando un array de NumPy (ndarray) a partir de la lista
array = np.array(lista)

print(f"Array de Python: {lista} de tipo {type(lista)}")
print(f"Array de NumPy: {array} de tipo {type(array)}")


Array de Python: [1, 2, 3, 4, 5] de tipo <class 'list'>
Array de NumPy: [1 2 3 4 5] de tipo <class 'numpy.ndarray'>


##### **Ejercicio 1** 
Imprimir en un array de Numpy los nros de 2, 4, .., 200

In [47]:
import numpy as np
lista=[]
for i in range(2, 201, 2):
  lista.append(i)
array=np.array(lista)
print(array)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [48]:
import numpy as np
numeros = np.arange(2, 201, 2)
print(numeros)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [49]:
lista=[2*x for x in range(1,101)]
array=np.array(lista)
print(array)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [50]:
# Creando un array a partir de una lista de Python
lista = [1, 2, 3, 4, 5]
# Creando un array de NumPy (ndarray) a partir de la lista
np_nros = np.array(lista)

## Otras propiedades de los arrays de NumPy
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 1
np_nros.size : 5
np_nros.shape : (5,)
np_nros.itemsize : 8
np_nros.data : <memory at 0x119a89c00>


**2. Trabajando con arreglos**

In [51]:
array_2d = [ [11, 15, 21],
               [33, 48 , 55],]

print(array_2d)

np_array_2d = np.array(array_2d)

print(np_array_2d)

[[11, 15, 21], [33, 48, 55]]
[[11 15 21]
 [33 48 55]]


In [52]:
print("np_array_2d.dtype :", np_array_2d.dtype)
print("np_array_2d.ndim :", np_array_2d.ndim)
print("np_array_2d.size :", np_array_2d.size)
print("np_array_2d.shape :", np_array_2d.shape)
print("np_array_2d.itemsize :", np_array_2d.itemsize)
print("np_array_2d.data :", np_array_2d.data)

np_array_2d.dtype : int64
np_array_2d.ndim : 2
np_array_2d.size : 6
np_array_2d.shape : (2, 3)
np_array_2d.itemsize : 8
np_array_2d.data : <memory at 0x119baaa80>


In [53]:
fila_1 = np.arange(2, 21, 2)
fila_2 = np.arange(1, 20, 2)
fila_3 = np.arange(10, 101, 10)

array_3d = np.array([fila_1, fila_2, fila_3])

print(array_3d)

[[  2   4   6   8  10  12  14  16  18  20]
 [  1   3   5   7   9  11  13  15  17  19]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [54]:
import numpy as np
fila1 = np.array([2*x for x in range(1, 11)])
fila2 = np.array([2*x - 1 for x in range(1, 11)])  
fila3 = np.array([10 + 20*x for x in range(0, 10)])
array=np.array([fila1, fila2, fila3])
print(array)

[[  2   4   6   8  10  12  14  16  18  20]
 [  1   3   5   7   9  11  13  15  17  19]
 [ 10  30  50  70  90 110 130 150 170 190]]


In [55]:
nros = [
    [ x for x in range(2,22,2)],
    [ y for y in range(1,21,2)],
    [ z for z in range(10,200,20)]
]
np_array = np.array(nros)
print(np_array)

[[  2   4   6   8  10  12  14  16  18  20]
 [  1   3   5   7   9  11  13  15  17  19]
 [ 10  30  50  70  90 110 130 150 170 190]]


In [56]:
import numpy as np

fila1 = []
fila2 = []
fila3 = []

# 10 primeros números pares
for x in range(2, 21, 2):
    fila1.append(x)

arrayf1=np.array(fila1)
print(np.array(arrayf1))



# 10 primeros números impares
for x in range(1, 20, 2):
    fila2.append(x)

arrayf2=np.array(fila2)
print(np.array(arrayf2))


# Secuencia 10, 30, 50, ..., 110
for x in range(10, 200, 20):
    fila3.append(x)

arrayf3=np.array(fila3)
print(np.array(arrayf3))

print(len(fila1), len(fila2), len(fila3))

arreglo = np.array([fila1, fila2, fila3])

print(arreglo)

[ 2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]
[ 10  30  50  70  90 110 130 150 170 190]
10 10 10
[[  2   4   6   8  10  12  14  16  18  20]
 [  1   3   5   7   9  11  13  15  17  19]
 [ 10  30  50  70  90 110 130 150 170 190]]


**3. Creación de arreglos NumPy**

Objetivo: practicar constructores frecuentes (zeros, ones, arange) para generar arreglos de forma rapida.

In [57]:
np_z = np.zeros((3, 4))  # Arreglo de ceros de 3 filas y 4 columnas    
print(np_z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
np_o = np.ones((2, 5))  # Arreglo de unos de 2 filas y 5 columnas    
print(np_o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
np_nros = np.arange(10, 51)  # Arreglo con valores desde 10 hasta 50
print(np_nros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**4. Operaciones básicas**

Objetivo: aplicar operaciones aritmeticas vectorizadas y comparar con listas tradicionales.

In [60]:
# Como sumamos a una lista un valor escalar?
arr1 = [x for x in range(4)]
## arr2 = arr1 + 8
print("arr1 :", arr1)

arr1 : [0, 1, 2, 3]


In [61]:
# SUMA CON NUMPY
np_arr1 = np.array(arr1)
print("np_arr1 :", np_arr1)

# Con ndarray de NumPy, podemos sumar un valor escalar a todos los elementos del array
np_arr2 = np_arr1 + 8
print("np_arr2 :", np_arr2)

np_arr1 : [0 1 2 3]
np_arr2 : [ 8  9 10 11]


In [62]:
# RESTA CON NUMPY
np_arr1 = np.array(arr1)
print("np_arr1 :", np_arr1)

# Con ndarray de NumPy, podemos restar un valor escalar a todos los elementos del array
np_arr2 = np_arr1 - 8
print("np_arr2 :", np_arr2)

np_arr1 : [0 1 2 3]
np_arr2 : [-8 -7 -6 -5]


In [63]:
# MULTIPLICACIÓN CON NUMPY
np_arr1 = np.array(arr1)
print("np_arr1 :", np_arr1)

# Con ndarray de NumPy, podemos multiplicar todos los elementos del array por un valor escalar
np_arr2 = np_arr1 * 8
print("np_arr2 :", np_arr2)

np_arr1 : [0 1 2 3]
np_arr2 : [ 0  8 16 24]


In [64]:
# DIVISIÓN CON NUMPY
np_arr1 = np.array(arr1)
print("np_arr1 :", np_arr1)

# Con ndarray de NumPy, podemos dividir todos los elementos del array por un valor escalar
np_arr2 = np_arr1 / 8
print("np_arr2 :", np_arr2)

np_arr1 : [0 1 2 3]
np_arr2 : [0.    0.125 0.25  0.375]


##### **Ejercicio 3**

Crea un arreglo de NumPy con la secuencia 10, 30, 50, ..., 130. Luego aplica en cadena estas operaciones:

- Divide todos los elementos entre 10.
- Resta 3 al resultado anterior.
- Suma 1 al resultado anterior.
- Multiplica por -1 el resultado final y muestralo.

Pista: usa una variable intermedia por cada paso para revisar tu proceso.

In [65]:
import numpy as np
array02 = np.arange(10, 131, 20)
print("Array principal:", array02)

paso1 = array02 / 10
print("dividido entre 10:", paso1)

paso2 = paso1 - 3
print("restando 3 al anterior resultado:", paso2)

paso3 = paso2 + 1
print("sumando 1 al anterior resultado:", paso3)

paso4 = paso3*-1
print("multiplicando por -1 al anterior resultado:", paso4)

Array principal: [ 10  30  50  70  90 110 130]
dividido entre 10: [ 1.  3.  5.  7.  9. 11. 13.]
restando 3 al anterior resultado: [-2.  0.  2.  4.  6.  8. 10.]
sumando 1 al anterior resultado: [-1.  1.  3.  5.  7.  9. 11.]
multiplicando por -1 al anterior resultado: [  1.  -1.  -3.  -5.  -7.  -9. -11.]


In [66]:
import numpy as np

arreglo1 = np.arange(10, 140, 20)

arreglo2= arreglo1 /10

arreglo3=arreglo2-3

arreglo4=arreglo3+1

arreglo5=arreglo4*-1

print(arreglo5)

[  1.  -1.  -3.  -5.  -7.  -9. -11.]


In [67]:
np_nros = np.arange(10, 131, 20)  # Arreglo con valores desde 10 hasta 130
print(np_nros)
#Divide todos los elementos entre 10
np_div = np_nros / 10
#print("np_div :", np_div)

#Resta 3 al resultado anterior. 
np_res = np_div-3
#print("np_res :", np_res)

#Suma 1 al resultado anterior. 
np_sum = np_res+1
#print("np_res :", np_sum)

#Multiplica por -1 el resultado final
np_mul = np_sum*-1
print("np_mul :", np_mul)

[ 10  30  50  70  90 110 130]
np_mul : [  1.  -1.  -3.  -5.  -7.  -9. -11.]


In [68]:
import numpy as np

a = np.array(range(10,131,20))
print("Original:", a)

b = a / 10
print("Dividir entre 10:", b)

c = b - 3
print("Restar 3:", c)

d = c + 1
print("Sumar 1:", d)

e = d * -1
print("Multiplicar por -1:", e)

Original: [ 10  30  50  70  90 110 130]
Dividir entre 10: [ 1.  3.  5.  7.  9. 11. 13.]
Restar 3: [-2.  0.  2.  4.  6.  8. 10.]
Sumar 1: [-1.  1.  3.  5.  7.  9. 11.]
Multiplicar por -1: [  1.  -1.  -3.  -5.  -7.  -9. -11.]


**5. Operaciones entre arreglos**

Objetivo: aplicar operaciones entre arreglos de Numpy.

In [71]:
np_arr1 = np.arange(4)
np_arr2 = np.arange(4, 8)

print("np_arr1 :", np_arr1)
print("np_arr2 :", np_arr2)

np_arr1 : [0 1 2 3]
np_arr2 : [4 5 6 7]


In [73]:
print("Suma de np_arr1 y np_arr2 :", np_arr1 + np_arr2)
print("Resta de np_arr1 y np_arr2 :", np_arr1 - np_arr2)
print("Multiplicación de np_arr1 y np_arr2 :", np_arr1 * np_arr2)
print("División de np_arr1 y np_arr2 :", np_arr1 / np_arr2)

Suma de np_arr1 y np_arr2 : [ 4  6  8 10]
Resta de np_arr1 y np_arr2 : [-4 -4 -4 -4]
Multiplicación de np_arr1 y np_arr2 : [ 0  5 12 21]
División de np_arr1 y np_arr2 : [0.         0.2        0.33333333 0.42857143]


In [77]:
np_arr1_extra = (np_arr1 / np_arr2)*np_arr2

print("np_arr1_extra :", np_arr1_extra)

np_arr1_extra : [0. 1. 2. 3.]


In [ ]:
# Funcion para convertir los elementos de un array a enteros
np_arr1_extra = np_arr1_extra.astype(int)

print("np_arr1_extra :", np_arr1_extra)

np_arr1_extra : [0 1 2 3]


##### **Ejercicio 4**

Se tienen los arreglos:

- [0, 1, 0]
- [1, 0, 0]
- [0, 0, 1]

Calcular:

- La suma entre arreglos.
- El producto entre arreglos.

Pista: define cada arreglo como np.array(...) y prueba operaciones elemento a elemento.



In [83]:
import numpy as np
arr1 = np.array([0, 1, 0])
arr2 = np.array([1, 0, 0])
arr3 = np.array([0, 0, 1])
suma = arr1 + arr2 + arr3

print("Suma:", suma)

multiplicacion = arr1 * arr2 * arr3
print("Producto:", multiplicacion)

Suma: [1 1 1]
Producto: [0 0 0]


In [84]:
import numpy as np

a = np.array([0,1,0])
b = np.array([1,0,0])
c = np.array([0,0,1])

print(a + b + c)
print(a * b * c)

[1 1 1]
[0 0 0]


**5. Producto de matrices**

Objetivo: interpretar el producto punto y su uso en operaciones matriciales.

<img src="imagenes/producto_punto.jpg" width="400" />



In [85]:
np_arr1 = np.arange(4)
np_arr2 = np.arange(4, 8)

print("np_arr1 :", np_arr1)
print("np_arr2 :", np_arr2)

np_arr1 : [0 1 2 3]
np_arr2 : [4 5 6 7]


In [92]:
# Producto punto de np_arr1 y np_arr2
print(sum(np_arr1 * np_arr2))

# Producto punto de np_arr1 y np_arr2
print(np.dot(np_arr1, np_arr2))
print(np_arr1.dot(np_arr2))

# Producto punto de np_arr2 y np_arr1
print(np.dot(np_arr2, np_arr1))
print(np_arr2.dot(np_arr1))


38
38
38
38
38


Cambiar la forma de un arreglo

In [93]:
np_arr = np.arange(12)  # Arreglo con valores del 0 al 11
print("Arreglo original:")
print(np_arr)

Arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [95]:
np_arr_reshaped = np_arr.reshape((3, 4))  # Cambiar la forma a 3 filas y 4 columnas
print("Arreglo con nueva forma (3x4):")
print(np_arr_reshaped)

Arreglo con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Ejercicio 5

Dados los vectores:",
- A = [3, 4],
- B = [2, 5],

Calcular:,

- El producto punto A · B,
- Las magnitudes |A| y |B|,

Pista: puedes usar np.dot y np.linalg.norm.